keys:
  # Users
  - &users:
    - &sven 58D48D664468351D3FDD46B4DDBD617F81BF84F4
  # Hosts
  - &hosts:
    - &beely age1ejxeh53gdz2chj6h0emyueqgajwh6sfrplqlhwuydp2tjz9wwshswk8jfk
    - &maja age1yg0rkr4e7g3lc4e8nx03je686gwttl32vszpe5whden4pln86d7sljp4yz
    - &willi age1d0rhdfel2a9s56wycpw5zxkkum2hntgekgpfsg8d9vlqawnp3sgqt50urx
    # - &bilbo

creation_rules:
 s - path_regex: home/common/secrets-home.ya?ml$
    key_groups:
    - age:
      - *maja
      - *willi
      pgp:
      - *sven

  # - path_regex: hosts/common/secrets-rps.ya?ml$
  #   key_groups:
  #   - age:
  #     - *bilbo
  #     - *dodo
  #     pgp:
  #     - *sven
