# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7fdf8d72-a698-46fb-ab08-cea26363d615";
      fsType = "btrfs";
      options = [ "subvol=@,compress=zstd" ];
    };

  # fileSystems."/media/beely" =
  #   { device = "systemd-1";
  #     fsType = "autofs";
  #   };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/7fdf8d72-a698-46fb-ab08-cea26363d615";
      fsType = "btrfs";
      options = [ "subvol=@home,compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/7fdf8d72-a698-46fb-ab08-cea26363d615";
      fsType = "btrfs";
      options = [ "subvol=@nix,compress=zstd" ];
    };

  # fileSystems."/swap" =
  #   { device = "/dev/disk/by-uuid/7fdf8d72-a698-46fb-ab08-cea26363d615";
  #     fsType = "btrfs";
  #     options = [ "subvol=@swap" ];
  #   };

  # fileSystems."/var/cache" =
  #   { device = "/dev/disk/by-uuid/7fdf8d72-a698-46fb-ab08-cea26363d615";
  #     fsType = "btrfs";
  #     options = [ "subvol=@cache" ];
  #   };

  # fileSystems."/var/log" =
  #   { device = "/dev/disk/by-uuid/7fdf8d72-a698-46fb-ab08-cea26363d615";
  #     fsType = "btrfs";
  #     options = [ "subvol=@log" ];
  #   };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/B47D-A777";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
