# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "cryptd" "aesni_intel"];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0a45afcb-7db4-4890-88ca-7612bb1cf85d";
      fsType = "btrfs";
      options = [ "subvol=@,compress=zstd" ];
    };

  boot.initrd.luks.devices."nix".device = "/dev/disk/by-uuid/97470c2c-e91f-4cc1-b534-34fbb19d3c73";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0a45afcb-7db4-4890-88ca-7612bb1cf85d";
      fsType = "btrfs";
      options = [ "subvol=@home,compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/0a45afcb-7db4-4890-88ca-7612bb1cf85d";
      fsType = "btrfs";
      options = [ "subvol=@nix,compress=zstd,noatime" ];
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/8C1C-028C";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0f3u1u1u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
